/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.ui;

import javax.swing.filechooser.FileNameExtensionFilter;
import sistema.archivos.Archivo;
import sistema.graficos.ArbolBinario;

/**
 *
 * @author bruno
 */
public class VentanaConfiguracion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConfiguracion
     */
    public VentanaConfiguracion() {
        initComponents();
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setAcceptAllFileFilterUsed(false);
        cargarListados();
        this.setVisible(true);
    }
    
    private void cargarListados(){
        CboxCargaArchivos.addItem("Capa 0 - Agua");
        CboxCargaArchivos.addItem("Capa 1 - Grama");
        CboxCargaArchivos.addItem("Capa 2 - Arboles");
        CboxCargaArchivos.addItem("Capa 3 - Carretera");
        CboxCargaArchivos.addItem("Capa 4 - Montaña");
        CboxCargaArchivos.addItem("Tropas Jugador 1");
        CboxCargaArchivos.addItem("Tropas Jugador 2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnCargarArchivo = new javax.swing.JButton();
        CboxCargaArchivos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGraficarArbolJ1 = new javax.swing.JButton();
        btnGraficarArbolJ2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        btnReporteCapas = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        fileChooser.getAccessibleContext().setAccessibleName("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ArmyClash - Servidor");
        setResizable(false);

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        jLabel1.setText("Log:");

        btnCargarArchivo.setText("Cargar Archivo");
        btnCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivo(evt);
            }
        });

        CboxCargaArchivos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CboxCargaArchivosItemStateChanged(evt);
            }
        });

        jLabel2.setText("Archivo");

        jLabel3.setText("Reportes");

        btnGraficarArbolJ1.setText("Arbol J1");
        btnGraficarArbolJ1.setActionCommand("");
        btnGraficarArbolJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarArbolJ1ActionPerformed(evt);
            }
        });

        btnGraficarArbolJ2.setText("Arbol J2");
        btnGraficarArbolJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarArbolJ2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Tropas");

        jLabel5.setText("Capas");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnReporteCapas.setText("Ver Reporte");
        btnReporteCapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteCapasActionPerformed(evt);
            }
        });

        jLabel6.setText("ArmyClash - Servidor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGraficarArbolJ2)
                            .addComponent(btnGraficarArbolJ1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnReporteCapas)
                                .addGap(35, 35, 35))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CboxCargaArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCargarArchivo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(44, 44, 44)))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCargarArchivo)
                            .addComponent(CboxCargaArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGraficarArbolJ1)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGraficarArbolJ2)
                            .addComponent(btnReporteCapas))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarArchivo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivo
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == fileChooser.APPROVE_OPTION) {
            Archivo archivo = new Archivo();
            if(CboxCargaArchivos.getSelectedIndex() < 5)
                archivo.cargarCapa(fileChooser.getSelectedFile().getAbsolutePath(), CboxCargaArchivos.getSelectedIndex());
            else//se le resta 4 debido a que hay 4 opciones antes, entonces el index que devuelve es un +4 hacia el numero de jugador que deberia ser 1 o 2
                archivo.cargarTropas(fileChooser.getSelectedFile().getAbsolutePath(), (CboxCargaArchivos.getSelectedIndex() - 4));
            txtLog.setText(txtLog.getText() + archivo.log);
        }
    }//GEN-LAST:event_btnCargarArchivo

    private void CboxCargaArchivosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CboxCargaArchivosItemStateChanged
        fileChooser.resetChoosableFileFilters();
        FileNameExtensionFilter filtro;
        btnCargarArchivo.setEnabled(true);
        if(CboxCargaArchivos.getSelectedIndex() < 5)
            filtro = new FileNameExtensionFilter(".map", "map");
        else{
            filtro = new FileNameExtensionFilter(".army", "army");
            //btnCargarArchivo.setEnabled(false);
        }
        fileChooser.setFileFilter(filtro);
    }//GEN-LAST:event_CboxCargaArchivosItemStateChanged

    private void btnGraficarArbolJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarArbolJ1ActionPerformed
        if(main.Main.arbolJugador1 != null){
            txtLog.setText(txtLog.getText() + "Graficando Arbol Jugador 1...\n");
            ArbolBinario graficador =  new ArbolBinario();
            graficador.graficarArbol(main.Main.arbolJugador1);
        }else{
            txtLog.setText(txtLog.getText() + "*!Imposible Graficar -> Arbol Vacio!*\n");
        }
    }//GEN-LAST:event_btnGraficarArbolJ1ActionPerformed

    private void btnGraficarArbolJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarArbolJ2ActionPerformed
        if(main.Main.arbolJugador2 != null){
            txtLog.setText(txtLog.getText() + "Graficando Arbol Jugador 2...\n");
            ArbolBinario graficador =  new ArbolBinario();
            graficador.graficarArbol(main.Main.arbolJugador2);
        }else{
            txtLog.setText(txtLog.getText() + "*!Imposible Graficar -> Arbol Vacio!*\n");
        }
    }//GEN-LAST:event_btnGraficarArbolJ2ActionPerformed

    private void btnReporteCapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteCapasActionPerformed
        try{
            //System.out.println(main.Main.arbolJugador1.obtenerContenidoArbol());
            //System.out.println(main.Main.arbolJugador2.obtenerContenidoArbol());
        }catch(Exception ex){
           
        }
    }//GEN-LAST:event_btnReporteCapasActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentanaConfiguracion().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboxCargaArchivos;
    private javax.swing.JButton btnCargarArchivo;
    private javax.swing.JButton btnGraficarArbolJ1;
    private javax.swing.JButton btnGraficarArbolJ2;
    private javax.swing.JButton btnReporteCapas;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
